Install the latest pip for python3.10
Current pip from python3-pip cannot load some external libs such as
html5lib, so we're getting errors like:

`ImportError: cannot import name 'html5lib' from 'pip._vendor'
(/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)`

This change gets the latest pip so the py310 tests run just fine.